import type { NextConfig } from "next";

const ContentSecurityPolicy = `
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://connect.facebook.net;
  style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
  font-src 'self' https://fonts.gstatic.com;
  img-src 'self' data: blob: https://images.unsplash.com https://*.supabase.co https://www.google-analytics.com https://www.facebook.com;
  connect-src 'self' https://*.supabase.co https://www.google-analytics.com https://www.facebook.com;
  frame-src 'self' https://www.google.com https://maps.google.com;
  frame-ancestors 'none';
  base-uri 'self';
  form-action 'self';
`.replace(/\n/g, ' ').trim();

const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: ContentSecurityPolicy,
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff',
  },
  {
    key: 'X-Frame-Options',
    value: 'DENY',
  },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(self)',
  },
];

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // ── WordPress wildcard patterns ──────────────────────────────────
      { source: '/author/:path*', destination: '/', permanent: true },
      { source: '/tag/:path*', destination: '/', permanent: true },
      { source: '/category/:path*', destination: '/blog', permanent: true },
      { source: '/web-stories/:path*', destination: '/', permanent: true },
      { source: '/pages/contact-us', destination: '/contact', permanent: true },
      { source: '/pages/financing', destination: '/fee-structure', permanent: true },
      { source: '/pages/:path*', destination: '/', permanent: true },
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/account/:path*', destination: '/', permanent: true },

      // ── About / Management / Trust ───────────────────────────────────
      { source: '/about-the-college', destination: '/about', permanent: true },
      { source: '/about-the-college/', destination: '/about', permanent: true },
      { source: '/the-management', destination: '/about/our-management', permanent: true },
      { source: '/the-management/', destination: '/about/our-management', permanent: true },
      { source: '/the-trust', destination: '/about/our-trust', permanent: true },
      { source: '/the-trust/', destination: '/about/our-trust', permanent: true },
      { source: '/vision-mission', destination: '/about/vision-mission', permanent: true },
      { source: '/vision-mission/', destination: '/about/vision-mission', permanent: true },

      // ── Contact ──────────────────────────────────────────────────────
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/contact-us/', destination: '/contact', permanent: true },
      { source: '/help-desk', destination: '/contact', permanent: true },
      { source: '/help-desk/', destination: '/contact', permanent: true },

      // ── Facilities ───────────────────────────────────────────────────
      { source: '/transport', destination: '/facilities/transport', permanent: true },
      { source: '/transport/', destination: '/facilities/transport', permanent: true },
      { source: '/auditorium', destination: '/facilities/auditorium', permanent: true },
      { source: '/auditorium/', destination: '/facilities/auditorium', permanent: true },
      { source: '/seminar-hall', destination: '/facilities/seminar-hall', permanent: true },
      { source: '/seminar-hall/', destination: '/facilities/seminar-hall', permanent: true },
      { source: '/class-room', destination: '/facilities/classroom', permanent: true },
      { source: '/class-room/', destination: '/facilities/classroom', permanent: true },
      { source: '/sports-club', destination: '/facilities/sports-club', permanent: true },
      { source: '/sports-club/', destination: '/facilities/sports-club', permanent: true },
      { source: '/wifi', destination: '/facilities', permanent: true },
      { source: '/wifi/', destination: '/facilities', permanent: true },
      { source: '/digital-campus', destination: '/facilities', permanent: true },
      { source: '/digital-campus/', destination: '/facilities', permanent: true },
      { source: '/emergency-care', destination: '/facilities', permanent: true },
      { source: '/emergency-care/', destination: '/facilities', permanent: true },

      // ── NIRF ─────────────────────────────────────────────────────────
      { source: '/nirf-2025', destination: '/nirf/nirf-2025', permanent: true },
      { source: '/nirf-2025/', destination: '/nirf/nirf-2025', permanent: true },
      { source: '/nirf-2', destination: '/nirf', permanent: true },
      { source: '/nirf-2/', destination: '/nirf', permanent: true },

      // ── IQAC ─────────────────────────────────────────────────────────
      { source: '/academic-calendar', destination: '/others/academic-calendar', permanent: true },
      { source: '/academic-calendar/', destination: '/others/academic-calendar', permanent: true },
      { source: '/role-responsibilities', destination: '/iqac/role-responsibilities', permanent: true },
      { source: '/role-responsibilities/', destination: '/iqac/role-responsibilities', permanent: true },
      { source: '/objectives-functions', destination: '/iqac/objectives-functions', permanent: true },
      { source: '/objectives-functions/', destination: '/iqac/objectives-functions', permanent: true },
      { source: '/minutes-of-iqac-meeting-3', destination: '/iqac/minutes-of-meeting', permanent: true },
      { source: '/minutes-of-iqac-meeting-3/', destination: '/iqac/minutes-of-meeting', permanent: true },

      // ── Misc pages ───────────────────────────────────────────────────
      { source: '/index.html', destination: '/', permanent: true },
      { source: '/camu', destination: '/', permanent: true },
      { source: '/camu/', destination: '/', permanent: true },
      { source: '/microsoft-365', destination: '/', permanent: true },
      { source: '/microsoft-365/', destination: '/', permanent: true },
      { source: '/google-workspace', destination: '/', permanent: true },
      { source: '/google-workspace/', destination: '/', permanent: true },
      { source: '/examination', destination: '/', permanent: true },
      { source: '/examination/', destination: '/', permanent: true },
      { source: '/alumni-insight', destination: '/', permanent: true },
      { source: '/alumni-insight/', destination: '/', permanent: true },
      { source: '/proud-moment', destination: '/', permanent: true },
      { source: '/proud-moment/', destination: '/', permanent: true },

      // ── Old event / blog posts ────────────────────────────────────────
      { source: '/exposure-visit-to-tex-valley', destination: '/events', permanent: true },
      { source: '/exposure-visit-to-tex-valley/', destination: '/events', permanent: true },
      { source: '/bridge-course-event-for-all-the-first-year', destination: '/events', permanent: true },
      { source: '/bridge-course-event-for-all-the-first-year/', destination: '/events', permanent: true },
      { source: '/world-ozone-day', destination: '/events', permanent: true },
      { source: '/world-ozone-day/', destination: '/events', permanent: true },
      { source: '/world-ozone-day-celebration', destination: '/events', permanent: true },
      { source: '/world-ozone-day-celebration/', destination: '/events', permanent: true },
      { source: '/national-handloom-day', destination: '/events', permanent: true },
      { source: '/national-handloom-day/', destination: '/events', permanent: true },
      { source: '/inter-collegiate-fashion-show-style-icons-25', destination: '/events', permanent: true },
      { source: '/inter-collegiate-fashion-show-style-icons-25/', destination: '/events', permanent: true },
      { source: '/women-leadership-forum-inauguration', destination: '/events', permanent: true },
      { source: '/women-leadership-forum-inauguration/', destination: '/events', permanent: true },
      { source: '/new-year-celebration', destination: '/events', permanent: true },
      { source: '/new-year-celebration/', destination: '/events', permanent: true },
      { source: '/hands-on-securities-market-bootcamp-from-theory-to-practice', destination: '/events', permanent: true },
      { source: '/hands-on-securities-market-bootcamp-from-theory-to-practice/', destination: '/events', permanent: true },
      { source: '/dazzle-2025-freshers-day-celebration', destination: '/events', permanent: true },
      { source: '/dazzle-2025-freshers-day-celebration/', destination: '/events', permanent: true },
      { source: '/knowledge-meets-industry-mou-day', destination: '/events', permanent: true },
      { source: '/knowledge-meets-industry-mou-day/', destination: '/events', permanent: true },
      { source: '/national-road-safety-week', destination: '/events', permanent: true },
      { source: '/national-road-safety-week/', destination: '/events', permanent: true },
      { source: '/zumba-dance-session-a-fun-filled-fitness-experience-for-our-facilitators', destination: '/events', permanent: true },
      { source: '/zumba-dance-session-a-fun-filled-fitness-experience-for-our-facilitators/', destination: '/events', permanent: true },
      { source: '/first-year-learners-induction-program', destination: '/events', permanent: true },
      { source: '/first-year-learners-induction-program/', destination: '/events', permanent: true },
      { source: '/workshop-on-short-story-writing', destination: '/events', permanent: true },
      { source: '/workshop-on-short-story-writing/', destination: '/events', permanent: true },
      { source: '/biotrakz-2k25', destination: '/events', permanent: true },
      { source: '/biotrakz-2k25/', destination: '/events', permanent: true },
      { source: '/freshers-development-internship-program', destination: '/events', permanent: true },
      { source: '/freshers-development-internship-program/', destination: '/events', permanent: true },
      { source: '/namma-campus-pongal', destination: '/events', permanent: true },
      { source: '/namma-campus-pongal/', destination: '/events', permanent: true },
      { source: '/the-inter-institutional-idea-challenge-7-0', destination: '/events', permanent: true },
      { source: '/the-inter-institutional-idea-challenge-7-0/', destination: '/events', permanent: true },
      { source: '/value-added-course-tnpsc-inaugural-and-orientation-program', destination: '/events', permanent: true },
      { source: '/value-added-course-tnpsc-inaugural-and-orientation-program/', destination: '/events', permanent: true },
      { source: '/unnati-foundation-program', destination: '/events', permanent: true },
      { source: '/unnati-foundation-program/', destination: '/events', permanent: true },
      { source: '/anti-ragging-awareness-program', destination: '/events', permanent: true },
      { source: '/anti-ragging-awareness-program/', destination: '/events', permanent: true },
      { source: '/faculty-development-programme-on-outcome-based-education', destination: '/events', permanent: true },
      { source: '/faculty-development-programme-on-outcome-based-education/', destination: '/events', permanent: true },
      { source: '/faculty-development-program-understanding-ai-acceleration-trends-and-tools', destination: '/events', permanent: true },
      { source: '/faculty-development-program-understanding-ai-acceleration-trends-and-tools/', destination: '/events', permanent: true },
      { source: '/workshop-on-effective-sales-and-marketing-for-entrepreneurs-startups', destination: '/events', permanent: true },
      { source: '/workshop-on-effective-sales-and-marketing-for-entrepreneurs-startups/', destination: '/events', permanent: true },
      { source: '/road-safety-awareness', destination: '/events', permanent: true },
      { source: '/road-safety-awareness/', destination: '/events', permanent: true },
      { source: '/chess-competition-with-regard-to-world-chess-day', destination: '/events', permanent: true },
      { source: '/chess-competition-with-regard-to-world-chess-day/', destination: '/events', permanent: true },
      { source: '/national-mathematics-day', destination: '/events', permanent: true },
      { source: '/national-mathematics-day/', destination: '/events', permanent: true },
      { source: '/plastic-awareness-rally', destination: '/events', permanent: true },
      { source: '/plastic-awareness-rally/', destination: '/events', permanent: true },
      { source: '/anti-drug-awareness-campaign', destination: '/events', permanent: true },
      { source: '/anti-drug-awareness-campaign/', destination: '/events', permanent: true },
      { source: '/hands-on-training-workshop', destination: '/events', permanent: true },
      { source: '/hands-on-training-workshop/', destination: '/events', permanent: true },
      { source: '/christmas-celebration', destination: '/events', permanent: true },
      { source: '/christmas-celebration/', destination: '/events', permanent: true },
      { source: '/empowering-tomorrows-lifesavers-yuva-clubs-world-restart-a-heart-day-event', destination: '/events', permanent: true },
      { source: '/empowering-tomorrows-lifesavers-yuva-clubs-world-restart-a-heart-day-event/', destination: '/events', permanent: true },

      // ── Programme redirects ───────────────────────────────────────────
      { source: '/msc-computer-science-data-analytics', destination: '/programmes/self-finance/pg/msc-cs-data-analytics', permanent: true },
      { source: '/msc-computer-science-data-analytics/', destination: '/programmes/self-finance/pg/msc-cs-data-analytics', permanent: true },
      { source: '/ph-d-zoology', destination: '/programmes/aided/phd/zoology', permanent: true },
      { source: '/ph-d-zoology/', destination: '/programmes/aided/phd/zoology', permanent: true },
      { source: '/p-h-d-chemistry', destination: '/programmes/aided/phd/chemistry', permanent: true },
      { source: '/p-h-d-chemistry/', destination: '/programmes/aided/phd/chemistry', permanent: true },
      { source: '/ph-d-tamil', destination: '/programmes/aided/phd/tamil', permanent: true },
      { source: '/ph-d-tamil/', destination: '/programmes/aided/phd/tamil', permanent: true },
      { source: '/b-sc-ai-ds', destination: '/programmes/self-finance/ug/bsc-ai-ds', permanent: true },
      { source: '/b-sc-ai-ds/', destination: '/programmes/self-finance/ug/bsc-ai-ds', permanent: true },
      { source: '/b-sc-chemistry', destination: '/programmes/aided/ug/bsc-chemistry', permanent: true },
      { source: '/b-sc-chemistry/', destination: '/programmes/aided/ug/bsc-chemistry', permanent: true },
      { source: '/b-c-a', destination: '/programmes/self-finance/ug/bca', permanent: true },
      { source: '/b-c-a/', destination: '/programmes/self-finance/ug/bca', permanent: true },
      { source: '/msc-physics', destination: '/programmes/aided/pg/msc-physics', permanent: true },
      { source: '/msc-physics/', destination: '/programmes/aided/pg/msc-physics', permanent: true },
      { source: '/m-sc-zoology', destination: '/programmes/aided/pg/msc-zoology', permanent: true },
      { source: '/m-sc-zoology/', destination: '/programmes/aided/pg/msc-zoology', permanent: true },
      { source: '/m-com', destination: '/programmes/aided/pg/mcom', permanent: true },
      { source: '/m-com/', destination: '/programmes/aided/pg/mcom', permanent: true },
      { source: '/m-a-english', destination: '/programmes/self-finance/pg/ma-english', permanent: true },
      { source: '/m-a-english/', destination: '/programmes/self-finance/pg/ma-english', permanent: true },
      { source: '/master-of-computer-application', destination: '/programmes/aided/pg/mca', permanent: true },
      { source: '/master-of-computer-application/', destination: '/programmes/aided/pg/mca', permanent: true },
      { source: '/ba-history', destination: '/programmes/aided/ug/ba-history', permanent: true },
      { source: '/ba-history/', destination: '/programmes/aided/ug/ba-history', permanent: true },
      { source: '/b-com-finance-and-analytics', destination: '/programmes/self-finance/ug/bcom-accounting-finance', permanent: true },
      { source: '/b-com-finance-and-analytics/', destination: '/programmes/self-finance/ug/bcom-accounting-finance', permanent: true },
      { source: '/m-phil-tamil', destination: '/programmes', permanent: true },
      { source: '/m-phil-tamil/', destination: '/programmes', permanent: true },
      { source: '/m-phil-zoology', destination: '/programmes', permanent: true },
      { source: '/m-phil-zoology/', destination: '/programmes', permanent: true },
      { source: '/m-phil-history', destination: '/programmes', permanent: true },
      { source: '/m-phil-history/', destination: '/programmes', permanent: true },
      { source: '/m-phil-computer-science', destination: '/programmes', permanent: true },
      { source: '/m-phil-computer-science/', destination: '/programmes', permanent: true },
      { source: '/m-phil-commerce', destination: '/programmes', permanent: true },
      { source: '/m-phil-commerce/', destination: '/programmes', permanent: true },

      // ── Department redirects ──────────────────────────────────────────
      { source: '/department-of-textile-and-fashion-designing', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-textile-and-fashion-designing/', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-textile-and-fashion-designing-sf', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-textile-and-fashion-designing-sf/', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-tfd', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-tfd/', destination: '/departments/self-finance/textile-fashion-designing', permanent: true },
      { source: '/department-of-visual-communication', destination: '/departments/self-finance/visual-communication', permanent: true },
      { source: '/department-of-visual-communication/', destination: '/departments/self-finance/visual-communication', permanent: true },
      { source: '/department-bsc-visual-communication', destination: '/departments/self-finance/visual-communication', permanent: true },
      { source: '/department-bsc-visual-communication/', destination: '/departments/self-finance/visual-communication', permanent: true },
      { source: '/department-of-tamil', destination: '/departments/aided/tamil', permanent: true },
      { source: '/department-of-tamil/', destination: '/departments/aided/tamil', permanent: true },
      { source: '/department-of-tamil-sf', destination: '/departments/self-finance/tamil', permanent: true },
      { source: '/department-of-tamil-sf/', destination: '/departments/self-finance/tamil', permanent: true },
      { source: '/department-of-mathematics', destination: '/departments/aided/mathematics', permanent: true },
      { source: '/department-of-mathematics/', destination: '/departments/aided/mathematics', permanent: true },
      { source: '/department-of-mathematics-aided', destination: '/departments/aided/mathematics', permanent: true },
      { source: '/department-of-mathematics-aided/', destination: '/departments/aided/mathematics', permanent: true },
      { source: '/department-of-english', destination: '/departments/aided/english', permanent: true },
      { source: '/department-of-english/', destination: '/departments/aided/english', permanent: true },
      { source: '/department-of-english-sf', destination: '/departments/self-finance/english', permanent: true },
      { source: '/department-of-english-sf/', destination: '/departments/self-finance/english', permanent: true },
      { source: '/department-of-physics', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-physics/', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-physics-allied', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-physics-allied/', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-physics-2', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-physics-2/', destination: '/departments/aided/physics', permanent: true },
      { source: '/department-of-history', destination: '/departments/aided/history', permanent: true },
      { source: '/department-of-history/', destination: '/departments/aided/history', permanent: true },
      { source: '/department-of-commerce', destination: '/departments/aided/commerce', permanent: true },
      { source: '/department-of-commerce/', destination: '/departments/aided/commerce', permanent: true },
      { source: '/department-of-commerce-sf', destination: '/departments/self-finance/commerce', permanent: true },
      { source: '/department-of-commerce-sf/', destination: '/departments/self-finance/commerce', permanent: true },
      { source: '/department-of-computer-science', destination: '/departments/aided/computer-science', permanent: true },
      { source: '/department-of-computer-science/', destination: '/departments/aided/computer-science', permanent: true },
      { source: '/department-of-computer-science-3', destination: '/departments/self-finance/computer-science', permanent: true },
      { source: '/department-of-computer-science-3/', destination: '/departments/self-finance/computer-science', permanent: true },
      { source: '/department-of-computer-applications-sf', destination: '/departments/self-finance/computer-applications', permanent: true },
      { source: '/department-of-computer-applications-sf/', destination: '/departments/self-finance/computer-applications', permanent: true },
      { source: '/department-of-physical-education', destination: '/departments/aided/physical-education', permanent: true },
      { source: '/department-of-physical-education/', destination: '/departments/aided/physical-education', permanent: true },
      { source: '/department-of-zoology', destination: '/departments/aided/zoology', permanent: true },
      { source: '/department-of-zoology/', destination: '/departments/aided/zoology', permanent: true },
      { source: '/department-of-library', destination: '/departments/aided/library', permanent: true },
      { source: '/department-of-library/', destination: '/departments/aided/library', permanent: true },
      { source: '/department-cyber-security', destination: '/departments/self-finance/cyber-security', permanent: true },
      { source: '/department-cyber-security/', destination: '/departments/self-finance/cyber-security', permanent: true },
      { source: '/department-of-microbiology-sf', destination: '/departments/self-finance/microbiology', permanent: true },
      { source: '/department-of-microbiology-sf/', destination: '/departments/self-finance/microbiology', permanent: true },
      { source: '/department-of-economics-sf', destination: '/departments', permanent: true },
      { source: '/department-of-economics-sf/', destination: '/departments', permanent: true },
      { source: '/department-of-botany', destination: '/departments', permanent: true },
      { source: '/department-of-botany/', destination: '/departments', permanent: true },
      { source: '/department-of-chemistry-sf', destination: '/departments', permanent: true },
      { source: '/department-of-chemistry-sf/', destination: '/departments', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: securityHeaders,
      },
    ];
  },
  experimental: {
    optimizeCss: true,
    optimizePackageImports: ['lucide-react', 'framer-motion'],
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: '*.supabase.co',
      },
    ],
  },
};

export default nextConfig;
